// server/models/Notification.js

const mongoose = require("mongoose");
const {
  NOTIFICATION_TYPES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_PRIORITIES,
} = require("../constants/notifications");

const notificationSchema = new mongoose.Schema(
  {
    // Owner — every query is scoped to this so a user only ever sees their own.
    // No standalone index here: the compound { userId, createdAt } and
    // { userId, isRead } indexes below both start with userId, so a separate
    // single-field userId index would be redundant (avoids over-indexing).
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    title:   { type: String, required: true, trim: true },
    message: { type: String, required: true, trim: true },

    // Semantic type — drives the frontend icon/colour (Module 1). Enumerated so
    // bad data can't slip in; extend the catalog in constants/notifications.js.
    type: {
      type: String,
      required: true,
      enum: NOTIFICATION_TYPES,
    },

    // Category filtering is always user-scoped (served by the userId compound
    // index) and is done client-side in Module 1/2, so no standalone index.
    category: {
      type: String,
      enum: NOTIFICATION_CATEGORIES,
      default: "system",
    },

    // lucide-react icon name — stored for records/future use (frontend maps its
    // own icon by `type`, so this is non-authoritative on the client).
    icon: { type: String, default: "Bell", trim: true },

    priority: {
      type: String,
      enum: NOTIFICATION_PRIORITIES,
      default: "normal",
    },

    // Unread state — served by the { userId, isRead } and { isRead, createdAt }
    // compound indexes below (no standalone index).
    isRead: { type: Boolean, default: false },

    // ── Admin campaign link (Module 4) ──────────────────────────────────────
    // Set only for notifications generated by an admin broadcast, linking each
    // delivered notification back to its NotificationCampaign for analytics.
    // null for all system-generated (Module 2) notifications — fully backward
    // compatible. Indexed via the partial-unique { campaignId, userId } below.
    campaignId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "NotificationCampaign",
      default: null,
    },

    // Prepared for future routing — a frontend path (e.g. "/my-bookings").
    link: { type: String, default: "", trim: true },

    // Free-form context (bookingId, service, amount, …) — never required.
    metadata: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { timestamps: true }
);

// ── Indexes (Module 5: rationalised — a small, purposeful set) ──────────────────
// 1) Primary list query: a user's notifications, newest first (also covers any
//    userId-only / userId+category scan via the userId prefix).
notificationSchema.index({ userId: 1, createdAt: -1 });
// 2) Unread-count / unread-filter query.
notificationSchema.index({ userId: 1, isRead: 1 });
// 3) Retention cleanup: delete READ notifications older than the cutoff.
notificationSchema.index({ isRead: 1, createdAt: 1 });
// 4) Campaign analytics ({ campaignId } lookups via the prefix) AND the
//    idempotency guarantee: at most ONE notification per (campaign, user), so a
//    re-dispatch after a crash/overlap can never create a duplicate. Partial so
//    only admin-sent docs (campaignId set) are indexed/constrained.
notificationSchema.index(
  { campaignId: 1, userId: 1 },
  { unique: true, partialFilterExpression: { campaignId: { $type: "objectId" } } }
);

module.exports = mongoose.model("Notification", notificationSchema);
